/* USERS */
export const GET_COMPANIES_OPTIONS = "GET_COMPANIES_OPTIONS";
export const GET_COMPANIES_OPTIONS_SUCCESS = "GET_COMPANIES_OPTIONS_SUCCESS";
export const GET_COMPANIES_OPTIONS_FAIL = "GET_COMPANIES_OPTIONS_FAIL";
