const express = require('express');
const app = express();
const cors = require('cors');
app.use(cors());
app.use(express.json());

const userRouter = require('./router/userRouter');
const privilegeRouter = require('./router/privilegeRouter');
const menuRouter = require('./router/menuRouter');
const unitRouter = require('./router/unitRouter');
const communityrequestRouter = require('./router/communityrequestRouter');
const categoryRouter = require('./router/categoryRouter');
const subcategoryRouter = require('./router/subcategoryRouter');
const thirdcategoryRouter = require('./router/thirdcategoryRouter');
const sliderRouter = require('./router/sliderRouter');
const supplierRouter = require('./router/supplierRouter');
const stateRouter = require('./router/stateRouter');
const stockRouter = require ('./router/stockRouter');
const stocklogRouter = require ('./router/stocklogRouter');
const orderRouter = require('./router/orderRouter');
const customerRouter = require('./router/customerRouter');
const multer = require('multer');
// const { sequelize } = require('./models/index');
app.use('/user', userRouter);
app.use('/privilege', privilegeRouter);
app.use('/menu', menuRouter);
app.use('/unit', unitRouter);
app.use('/communityrequest',communityrequestRouter);
app.use('/category',categoryRouter);
app.use('/subcategory',subcategoryRouter);
app.use('/thirdcategory',thirdcategoryRouter);
app.use('/slider',sliderRouter);
app.use('/supplier',supplierRouter);
app.use('/state',stateRouter);
app.use('/stock', stockRouter);
app.use('/stocklog', stocklogRouter);
app.use('/vieworders', orderRouter);
app.use('/customer',customerRouter);
const Port = process.env.PORT || 3099;

app.listen(Port, console.log('running'));
