/* USERS */
export const GET_PRIVILAGES_OPTIONS = "GET_PRIVILAGES_OPTIONS";
export const GET_PRIVILAGES_OPTIONS_SUCCESS = "GET_PRIVILAGES_OPTIONS_SUCCESS";
export const GET_PRIVILAGES_OPTIONS_FAIL = "GET_PRIVILAGES_OPTIONS_FAIL";
